export const GET_ORDER_LIST = 'BS/ORDER/GET_ORDER_LIST';
export const GET_ORDER_LIST_SUCCESS = 'BS/ORDER/GET_ORDER_LIST_SUCCESS';
export const INIT_PAGINATION = 'BS/ORDER/INIT_PAGINATION'
export const NEXT_PAGE = 'BS/ORDER/NEXT_PAGE'
export const PREV_PAGE = 'BS/ORDER/PREV_PAGE'


/*
 * 取消订单
 * 页面:订单列表  订单详情
 *
 * */

export const CANCLE_ORDER = 'BS/APP/ORDER_LIST/CANCLE_ORDER'
export const CANCLE_ORDER_SUCCESS = 'BS/APP/ORDER_LIST/CANCLE_ORDER_SUCCESS'
export const CANCLE_ORDER_ERROR = 'BS/APP/ORDER_LIST/CANCLE_ORDER_ERROR'
export const CONFIRM_RECEIVE = 'BS/APP/ORDER_LIST/CONFIRM_RECEIVE'


