export const GET_COMMEND_LIST = 'BS/COMMEND/GET_COMMEND_LIST';
export const GET_COMMEND_LIST_SUCCESS = 'BS/COMMEND/GET_COMMEND_LIST_SUCCESS';
export const GET_COMMEND_LIST_ERROR = 'BS/COMMEND/GET_COMMEND_LIST_ERROR';


