export const GET_PRODUCTS = 'BS/COLLECT/GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'BS/COLLECT/GET_PRODUCTS_SUCCESS';
export const INIT_PAGINATION = 'BS/COLLECT/INIT_PAGINATION'
export const NEXT_PAGE = 'BS/COLLECT/NEXT_PAGE'
export const PREV_PAGE = 'BS/COLLECT/PREV_PAGE'


