export const GET_ORDER_DETAIL = 'BS/ORDER/DETAIL/GET_ORDER_DETAIL'
export const GET_ORDER_DETAIL_SUCCESS = 'BS/ORDER/DETAIL/GET_ORDER_DETAIL_SUCCESS'
export const GET_ORDER_DETAIL_ERROR = 'BS/ORDER/DETAIL/GET_ORDER_DETAIL_ERROR'

export const CANCLE_ORDER = 'BS/APP/ORDER/CANCLE_ORDER'
export const CANCLE_ORDER_SUCCESS = 'BS/APP/ORDER/CANCLE_ORDER_SUCCESS'
export const CANCLE_ORDER_ERROR = 'BS/APP/ORDER/CANCLE_ORDER_ERROR'
export const CONFIRM_RECEIVE = 'BS/APP/ORDER/CONFIRM_RECEIVE'

export const GET_EXPRESS_SUCCESS = 'BS/ORDER/DETAIL/GET_EXPRESS_SUCCESS'
export const GET_EXPRESS_ERROR = 'BS/ORDER/DETAIL/GET_EXPRESS_ERROR'
export const GET_EXPRESS_EMPTY = 'BS/ORDER/DETAIL/GET_EXPRESS_EMPTY'
