export const GET_PRODUCT_DATA = 'BS/PRODUCT/GET_PRODUCT_DATA'
export const GET_PRODUCT_DATA_SUCCESS = 'BS/PRODUCT/GET_PRODUCT_DATA_SUCCESS'
export const GET_PRODUCT_DATA_ERROR = 'BS/PRODUCT/GET_PRODUCT_DATA_ERROR'

export const SET_PRODUCT_OPTION = 'BS/PRODUCT/SET_PRODUCT_OPTION'

export const ADD_COUNT = 'BS/PRODUCT/ADD_COUNT'
export const MINUS_COUNT = 'BS/PRODUCT/MINUS_COUNT'
export const CHANGE_COUNT = 'BS/PRODUCT/CHANGE_COUNT'

export const COLLECT = 'BS/PRODUCT/DETAIL/COLLECT'
export const COLLECT_SUCCESS = 'BS/PRODUCT/DETAIL/COLLECT_SUCCESS'


export const GET_PAYMENT_DATA = 'BS/PRODUCTDETAIL/GET_PAYMENT_DATA'
export const GET_PAYMENT_DATA_SUCCESS = 'BS/PRODUCTDETAIL/GET_PAYMENT_DATA_SUCCESS'


