export const GET_CAT = 'BS/CAT/GET_CAT';
export const GET_CAT_SUCCESS = 'BS/CAT/GET_CAT_SUCCESS';
export const CHANGE_ACTIVE_CAT = 'BS/CAT/CHANGE_ACTIVE_CAT';
export const GET_PRODUCTS = 'BS/CAT/GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'BS/CAT/GET_PRODUCTS_SUCCESS';
export const INIT_PAGINATION = 'BS/CAT/INIT_PAGINATION'
export const NEXT_PAGE = 'BS/CAT/NEXT_PAGE'
export const PREV_PAGE = 'BS/CAT/PREV_PAGE'


