export const GET_SLIDER_LIST = 'BS/SLIDER/GET_SLIDER_LIST';
export const GET_SLIDER_LIST_SUCCESS = 'BS/SLIDER/GET_SLIDER_LIST_SUCCESS';
export const GET_SLIDER_LIST_ERROR = 'BS/SLIDER/GET_SLIDER_LIST_ERROR';


