export const GET_COUPON_LIST = 'BS/COUPON/GET_COUPON_LIST';
export const GET_COUPON_LIST_SUCCESS = 'BS/COUPON/GET_COUPON_LIST_SUCCESS';
export const GET_COUPON_LIST_ERROR = 'BS/COUPON/GET_COUPON_LIST_ERROR';


export const GET_ENABLE_COUPON = 'BS/COUPON/GET_ENABLE_COUPON'
export const GET_ENABLE_COUPON_SUCCESS = 'BS/COUPON/GET_ENABLE_COUPON_SUCCESS'
