/*
 * AppConstants
 * Each action has a corresponding type, which the reducer knows and picks up on.
 * To avoid weird typos between the reducer and the actions, we save them as
 * constants here. We prefix them with 'yourproject/YourComponent' so we avoid
 * reducers accidentally picking up actions they shouldn't.
 *
 * Follow this format:
 * export const YOUR_ACTION_CONSTANT = 'yourproject/YourContainer/YOUR_ACTION_CONSTANT';
 */

export const GLOBAL_PAY = 'BS/ORDER/GLOBAL_PAY';
export const CHANGE_NORMAL_VALUE = 'BS/APP/CHANGE_NORMAL_VALUE'
export const LOAD_REPOS = 'boilerplate/App/LOAD_REPOS';
export const LOAD_REPOS_SUCCESS = 'boilerplate/App/LOAD_REPOS_SUCCESS';
export const LOAD_REPOS_ERROR = 'boilerplate/App/LOAD_REPOS_ERROR';
export const DEFAULT_LOCALE = 'en';



export const GET_ACCOUNT_INFO = 'BS/APP/GET_ACCOUNT_INFO'
export const GET_ACCOUNT_INFO_SUCCESS = 'BS/APP/GET_ACCOUNT_INFO_SUCCESS'
export const START_EDIT_ACCOUNT_INFO = 'BS/APP/START_EDIT_ACCOUNT_INFO'
export const EDIT_ACCOUNT_INFO = 'BS/APP/EDIT_ACCOUNT_INFO'
export const EDIT_ACCOUNT_INFO_SUCCESS = 'BS/APP/EDIT_ACCOUNT_INFO_SUCCESS'


export const LOGIN = 'BS/App/LOGIN'
export const LOGIN_ERROR = 'BS/App/LOGIN_ERROR'
export const LOGIN_SUCCESS = 'BS/App/LOGIN_SUCCESS'


export const SEARCH = 'BS/App/SEARCH'
export const SEARCH_SUCCESS = 'BS/App/SEARCH_SUCCESS'
export const SEARCH_ERROR = 'BS/App/SEARCH_ERROR'

export const SET_PAGINATION = 'BS/App/SET_PAGINATION'


export const ADD_CART_ITEM = 'BS/App/ADD_CART_ITEM'
export const ADD_CART_ITEM_SUCCESS = 'BS/App/ADD_CART_ITEM_SUCCESS'

export const DELETE_CART_ITEM = 'BS/App/DELETE_CART_ITEM'
export const DELETE_CART_ITEM_SUCCESS = 'BS/App/DELETE_CART_ITEM_SUCCESS'

export const GET_CART_DATA = 'BS/CART/GET_CART_DATA'
export const GET_CART_DATA_SUCCESS = 'BS/CART/GET_CART_DATA_SUCCESS'

export const CHANGE_CART_ITEM_COUNT = 'BS/CART/CHANGE_CART_ITEM_COUNT'
export const CHANGE_CART_ITEM_CHECKBOX = 'BS/CART/CHANGE_CART_ITEM_CHECKBOX'

// 地区列表
export const GET_ADDRESS_LIST = 'BS/App/GET_ADDRESS_LIST'
export const GET_ADDRESS_LIST_SUCCESS = 'BS/App/GET_ADDRESS_LIST_SUCCESS'
export const GET_ADDRESS_LIST_ERROR = 'BS/App/GET_ADDRESS_LIST_ERROR'

export const GET_CITY_LIST_BY_PROV = 'BS/App/GET_CITY_LIST_BY_PROV'
export const GET_CITY_LIST_BY_PROV_SUCCESS = 'BS/App/GET_CITY_LIST_BY_PROV_SUCCESS'

export const GET_DISTRICT_LIST_BY_CITY = 'BS/App/GET_DISTRICT_LIST_BY_CITY'
export const GET_DISTRICT_LIST_BY_CITY_SUCCESS = 'BS/App/GET_DISTRICT_LIST_BY_CITY_SUCCESS'


export const ADD_ADDRESS = 'BS/ADDRESS/ADD_ADDRESS'
export const ADD_ADDRESS_SUCCESS = 'BS/ADDRESS/ADD_ADDRESS_SUCCESS'
export const ADD_ADDRESS_ERROR = 'BS/ADDRESS/ADD_ADDRESS_ERROR'

export const DELETE_ADDRESS = 'BS/ADDRESS/DELETE_ADDRESS'
export const DELETE_ADDRESS_SUCCESS = 'BS/ADDRESS/DELETE_ADDRESS_SUCCESS'

export const EDIT_ADDRESS = 'BS/ADDRESS/EDIT_ADDRESS'
export const EDIT_ADDRESS_SUCCESS = 'BS/ADDRESS/EDIT_ADDRESS_SUCCESS'

export const SET_DEFAULT_ADDRESS = 'BS/ADDRESS/SET_DEFAULT_ADDRESS'
export const RESET_ADDRESS_FORM = 'BS/ADDRESS/RESET_ADDRESS_FORM'
export const RESET_ADDRESS_VALID = 'BS/ADDRESS/RESET_ADDRESS_VALID'

// invoice
export const GET_INVOICE = 'BS/INVOICE/GET_INVOICE'
export const GET_INVOICE_SUCCESS = 'BS/INVOICE/GET_INVOICE_SUCCESS'

export const ADD_INVOICE = 'BS/INVOICE/ADD_INVOICE'
export const ADD_INVOICE_SUCCESS = 'BS/INVOICE/ADD_INVOICE_SUCCESS'

export const EDIT_INVOICE = 'BS/INVOICE/EDIT_INVOICE'
export const EDIT_INVOICE_SUCCESS = 'BS/INVOICE/EDIT_INVOICE_SUCCESS'


export const ORDER_EDIT_INVOICE = 'BS/INVOICE/EDIT_INVOICE'
export const ORDER_EDIT_INVOICE_SUCCESS = 'BS/INVOICE/EDIT_INVOICE_SUCCESS'


export const DELETE_INVOICE = 'BS/INVOICE/DELETE_INVOICE'
export const DELETE_INVOICE_SUCCESS = 'BS/INVOICE/DELETE_INVOICE_SUCCESS'
export const SET_DEFAULT_INVOICE = 'BS/INVOICE/SET_DEFAULT_INVOICE'

export const SELECT_INVOICE_TYPE = 'BS/INVOICE/SELECT_INVOICE_TYPE'
export const SELECT_INVOICE_ITEM = 'BS/INVOICE/SELECT_INVOICE_ITEM'
export const RELOAD_INVOICE_SUCCESS = 'BS/INVOICE/RELOAD_INVOICE_SUCCESS'

export const RESET_ORDER_INVOICE_MODIFY = 'BS/INVOICE/RESET_ORDER_INVOICE_MODIFY'
export const SET_ORDER_INVOICE = 'BS/INVOICE/SET_ORDER_INVOICE'
export const ADD_ORDER_INVOICE = 'BS/INVOICE/ADD_ORDER_INVOICE'
export const HIDE_INVOICE_MODAL = 'BS/INVOICE/HIDE_INVOICE_MODAL'
export const RESET_ORDER_FORM = 'BS/INVOICE/RESET_ORDER_FORM'
export const RESET_INVOICE_VALID = 'BS/INVOICE/RESET_INVOICE_VALID'



// 快递方式
export const GET_DELIVERY = 'BS/DELIVERY/GET_DELIVERY'
export const GET_DELIVERY_SUCCESS = 'BS/DELIVERY/GET_DELIVERY_SUCCESS'
export const SELECT_DELIVERY = 'BS/DELIVERY/SELECT_DELIVERY'


export const GET_PAYMENT_DATA = 'BS/ORDER/GET_PAYMENT_DATA'
export const GET_PAYMENT_DATA_SUCCESS = 'BS/ORDER/GET_PAYMENT_DATA_SUCCESS'


export const ORDER_PAY = 'BS/ORDER/ORDER_PAY'
export const ORDER_PAY_SUCCESS = 'BS/ORDER/ORDER_PAY_SUCCESS'


export const SELECT_COUPON = 'BS/ORDER/SELECT_COUPON'

// 通用

export const CHANGE_SIMPLE_VALUE = 'BS/App/CHANGE_SIMPLE_VALUE'
// XFORM
export const ON_INPUT_CHANGE = 'BS/App/XFORM/ON_INPUT_CHANGE'


export const FETCH_LIST_DATA = 'BS/App/FETCH_LIST_DATA'
export const FETCH_LIST_DATA_SUCCESS = 'BS/App/FETCH_LIST_DATA_SUCCESS'

export const BUILD_ORDER_SUCCESS = 'BS/APP/ORDER/BUILD_ORDER_SUCCESS'






